os: linux
dist: focal
language: python

python:
  - "3.7"
  - "3.8"
  - "3.9"

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install flake8
  - pip install coveralls

before_script:
  - flake8 edc_protocol_register

script:
  -  python manage.py test
  -  python manage.py check
  - coverage run --source=edc-form-validators manage.py test

after_success:
  - coveralls
