# Generated by Django 3.0.5 on 2020-04-16 15:43

from django.db import migrations, models
import django.db.models.deletion
import edc_protocol_register.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocolRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=50, verbose_name='Protocol short name')),
                ('long_name', models.CharField(max_length=250, verbose_name='Protocol long name')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='protocol description')),
                ('email', models.EmailField(max_length=200, verbose_name='email')),
                ('pi_email', models.EmailField(max_length=200, verbose_name='PI email')),
                ('request_date', models.DateTimeField(verbose_name='requested date')),
                ('duration', models.DurationField(blank=True, help_text='study duration', null=True, verbose_name='duration of study')),
            ],
            options={
                'ordering': ['-request_date'],
                'permissions': [('can_approve_request', 'user can approve request'), ('can_reject_request', 'user can reject request')],
            },
        ),
        migrations.CreateModel(
            name='ProtocolResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], default='P', max_length=50, verbose_name='protocol status')),
                ('response_date', models.DateField(verbose_name='date of response')),
                ('protocol_request', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request', to='edc_protocol_register.ProtocolRequest')),
            ],
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=50, verbose_name='Protocol short name')),
                ('long_name', models.CharField(max_length=250, verbose_name='Protocol long name')),
                ('number', models.IntegerField(blank=True, validators=[edc_protocol_register.validators.validate_protocol_number], verbose_name='assigned protocol number')),
                ('approval_date', models.DateTimeField(verbose_name='date of approval')),
                ('protocol_response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='edc_protocol_register.ProtocolResponse')),
            ],
        ),
    ]
