# Generated by Django 3.0.4 on 2020-03-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_protocol_register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protocol',
            name='name',
        ),
        migrations.RemoveField(
            model_name='protocolrequest',
            name='name',
        ),
        migrations.AddField(
            model_name='protocol',
            name='long_name',
            field=models.CharField(default='', max_length=250, verbose_name='Protocol long name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='protocol',
            name='short_name',
            field=models.CharField(default='', max_length=50, verbose_name='Protocol short name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='protocolrequest',
            name='long_name',
            field=models.CharField(default='', max_length=250, verbose_name='Protocol long name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='protocolrequest',
            name='short_name',
            field=models.CharField(default='', max_length=50, verbose_name='Protocol short name'),
            preserve_default=False,
        ),
    ]
