# Generated by Django 2.2 on 2019-07-31 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edc_protocol_register', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='protocolresponse',
            options={'permissions': [('can_approve_request', 'user can approve request'), ('can_reject_request', 'user can reject request')]},
        ),
    ]
