# Generated by Django 3.0.5 on 2020-04-16 15:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('edc_protocol_register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolrequest',
            name='request_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='requested date'),
        ),
    ]
