# Generated by Django 4.2.5 on 2023-09-18 13:20

from django.db import migrations, models
import edc_base.utils


class Migration(migrations.Migration):

    dependencies = [
        ('edc_protocol_register', '0002_auto_20200416_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='long_name',
            field=models.CharField(max_length=500, verbose_name='Protocol long name'),
        ),
        migrations.AlterField(
            model_name='protocolrequest',
            name='long_name',
            field=models.CharField(max_length=500, verbose_name='Protocol long name'),
        ),
        migrations.AlterField(
            model_name='protocolresponse',
            name='response_date',
            field=models.DateField(default=edc_base.utils.get_utcnow, verbose_name='date of response'),
        ),
    ]
